// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReceiveMessages() {
  return window['go']['tcpclient']['TCPClient']['ReceiveMessages']();
}

export function SendAutoConnectServer(arg1) {
  return window['go']['tcpclient']['TCPClient']['SendAutoConnectServer'](arg1);
}

export function StartClient(arg1, arg2) {
  return window['go']['tcpclient']['TCPClient']['StartClient'](arg1, arg2);
}
