// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function ReceiveMessages():Promise<void>;

export function SendAutoConnectServer(arg1:number):Promise<void>;

export function StartClient(arg1:string,arg2:number):Promise<boolean>;
