// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseServerAndDisconnectClient():Promise<void>;

export function GetPort():Promise<number>;

export function ReStartServer():Promise<void>;

export function ReceiveMessages():Promise<void>;

export function SetServerPort(arg1:number):Promise<boolean>;
