// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort():Promise<number>;

export function ReceiveMessages():Promise<void>;

export function SetServerPort(arg1:number):Promise<boolean>;
