// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseServerAndDisconnectClient() {
  return window['go']['tcpserver']['TCPServer']['CloseServerAndDisconnectClient']();
}

export function GetPort() {
  return window['go']['tcpserver']['TCPServer']['GetPort']();
}

export function ReStartServer() {
  return window['go']['tcpserver']['TCPServer']['ReStartServer']();
}

export function SetServerPort(arg1) {
  return window['go']['tcpserver']['TCPServer']['SetServerPort'](arg1);
}
