// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['tcpserver']['TCPServer']['Close']();
}

export function SetServerPort(arg1) {
  return window['go']['tcpserver']['TCPServer']['SetServerPort'](arg1);
}
