// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort() {
  return window['go']['tcpserver']['TCPServer']['GetPort']();
}

export function ReceiveMessages() {
  return window['go']['tcpserver']['TCPServer']['ReceiveMessages']();
}

export function SendDirectoryContent(arg1) {
  return window['go']['tcpserver']['TCPServer']['SendDirectoryContent'](arg1);
}

export function SendFile(arg1) {
  return window['go']['tcpserver']['TCPServer']['SendFile'](arg1);
}

export function SetServerPort(arg1) {
  return window['go']['tcpserver']['TCPServer']['SetServerPort'](arg1);
}
