// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitialConnectServerPage() {
  return window['go']['initial']['Initial']['InitialConnectServerPage']();
}

export function InitialInputPortPage() {
  return window['go']['initial']['Initial']['InitialInputPortPage']();
}

export function InitialSnycDirectoryListPage() {
  return window['go']['initial']['Initial']['InitialSnycDirectoryListPage']();
}
