// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitialConnectServerPage(arg1) {
  return window['go']['initial']['Initial']['InitialConnectServerPage'](arg1);
}

export function InitialInputPortPage() {
  return window['go']['initial']['Initial']['InitialInputPortPage']();
}

export function InitialSnycDirectoryListPage() {
  return window['go']['initial']['Initial']['InitialSnycDirectoryListPage']();
}
