// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitialConnectServerPage():Promise<void>;

export function InitialInputPortPage():Promise<void>;

export function InitialSnycDirectoryListPage():Promise<void>;
