// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function ReloadApp() {
  return window['go']['main']['App']['ReloadApp']();
}
