// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CustomErrorDialog(arg1:string):Promise<void>;

export function OpenDirectory():Promise<main.ResponseFileStruct>;
