// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenDirectory():Promise<main.ResponseFileStruct>;

export function ReloadApp():Promise<void>;

export function ShowConnectWindow():Promise<void>;
